sudo: false
language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-26
    
    --scan
    
before_install:
  - chmod +x gradlew

